os:
  - linux
  - osx

language: node_js
node_js:
  - '12'
  - '11'
  - '10'

cache:
  directories:
    - node_modules

script:
  - echo $TRAVIS_OS_NAME
  - node --version
  - npm --version
  - echo "Testing started ..."
  - npm test

stages:
  - test
  - pack
  - name: deploy
    if: (type = push) AND branch =~ ^(master|v\d+\.\d+)$

jobs:
  include:
    - stage: pack
      script:
        - ./scripts/generate-version.ts
        - npm run test:pack
        - echo 'Npm Pack Testing Finished.'

    - stage: deploy
      script:
        - echo "Deploying to NPM ..."
        - npm version
        - if ./scripts/development-release.ts; then ./scripts/package-publish-config-tag-next.ts; fi
        - ./scripts/generate-version.ts
        - npm run dist

      deploy:
        provider: npm
        email: zixia@zixia.net
        api_key: "$NPM_TOKEN"
        skip_cleanup: true

notifications:
  email:
    on_success: change
    on_failure: change
